import { PageSection } from '@/types/database.types';
import { SectionDefinition, SectionType, SectionSettings } from './types';
import { defaultHeroTrustChips } from '@/lib/data/seed-data';

export const SECTION_DEFINITIONS: Record<SectionType, SectionDefinition> = {
  navigation: {
    type: 'navigation',
    title: 'Global Navigation',
    description: 'Site header with logo, navigation links, theme toggle, and primary CTA button.',
    category: 'core',
    iconName: 'Navigation',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: false,
      supportsSpacing: false,
      supportsAnimation: false,
      supportsVisibility: true,
    },
    defaultSettings: {
      heading: 'AnisShopify',
      primary_cta_label: "Let's Talk",
      primary_cta_url: '#contact',
      sticky_nav: true,
      transparent_over_hero: true,
      show_theme_toggle: true,
      nav_links: [
        { label: 'Home', href: '#home' },
        { label: 'Work', href: '#work' },
        { label: 'Services', href: '#services' },
        { label: 'About', href: '#about' },
        { label: 'FAQ', href: '#faq' },
        { label: 'Contact', href: '#contact' },
      ],
    },
  },
  hero: {
    type: 'hero',
    title: 'Hero Section',
    description: 'High-converting above-the-fold headline, developer bio, CTA buttons, and interactive visual showcase.',
    category: 'core',
    iconName: 'Sparkles',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Shopify Developer & Landing Page Specialist',
      heading: 'Shopify Website Design That',
      heading_prefix: 'Shopify Website Design That',
      rotating_words: [
        'Drives Growth',
        'Boosts Sales',
        'Elevates Brands',
        'Generates Results',
      ],
      hero_trust_chips: defaultHeroTrustChips,
      subheading:
        "Hey, I'm Ansarul Anis. A passionate young Shopify developer engineering custom high-converting stores, direct-response landing pages, and lightning-fast themes built to turn traffic into revenue.",
      primary_cta_label: 'View My Work',
      primary_cta_url: '#work',
      secondary_cta_label: 'Contact Me',
      secondary_cta_url: '#contact',
      badge_top_title: 'Top Rated',
      badge_top_subtitle: 'Shopify Developer',
      badge_bottom_title: '270+ Stores',
      badge_bottom_subtitle: 'Developed Successfully',
      image_url: '/images/ansarul-anis.png',
      image_alt: 'Ansarul Anis - Shopify Developer',
      image_position: 'right',
      layout: 'two-column',
      alignment: 'left',
      background: 'default',
      spacing_top: 'normal',
      spacing_bottom: 'normal',
      animation: 'fade-up',
      animation_speed: 'normal',
    },
  },
  trust_bar: {
    type: 'trust_bar',
    title: 'Trust Bar',
    description: 'Strip of key achievements, conversion lifts, client count, and freelancing track record.',
    category: 'core',
    iconName: 'Award',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: false,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
      supportsBlocks: true,
    },
    defaultSettings: {
      layout: 'four-column',
      background: 'default',
      spacing_top: 'compact',
      spacing_bottom: 'compact',
      animation: 'fade-up',
      blocks: [
        { id: 'ts-1', type: 'stat', stat_value: '4+', stat_label: 'Years Freelancing' },
        { id: 'ts-2', type: 'stat', stat_value: '270+', stat_label: 'Shopify Stores Built' },
        { id: 'ts-3', type: 'stat', stat_value: '99.8%', stat_label: 'Client Satisfaction' },
        { id: 'ts-4', type: 'stat', stat_value: '3.4x', stat_label: 'Avg. Conversion Lift' },
      ],
    },
  },
  work: {
    type: 'work',
    title: 'Work / Case Studies',
    description: 'Interactive case studies showing before/after results, challenge, solution, and conversion lift.',
    category: 'core',
    iconName: 'FolderGit2',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Case Studies',
      heading: 'Shopify Stores Built for Maximum Conversion',
      subheading:
        'Real results from custom Shopify website design, Shopify store redesign, and high-converting ecommerce website builds.',
      show_filters: true,
      layout: 'grid',
      columns: 3,
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  services: {
    type: 'services',
    title: 'Services',
    description: 'Specialized offerings from bespoke theme builds to headless Shopify and landing page optimization.',
    category: 'core',
    iconName: 'ShoppingBag',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'What I Do',
      heading: 'Complete Shopify Development Services',
      subheading:
        'From Shopify store design to headless ecommerce, every service is engineered to help you build a Shopify store that drives revenue.',
      featured_count: 3,
      layout: 'three-column',
      background: 'muted',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  testimonials: {
    type: 'testimonials',
    title: 'Testimonials',
    description: 'Client quotes, avatar photos, store revenue lift metrics, and company logos.',
    category: 'core',
    iconName: 'MessageSquareQuote',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Client Results',
      heading: 'Trusted by Ecommerce Brands Worldwide',
      subheading: 'See how expert Shopify website design and development transformed conversion rates and revenue.',
      carousel_autoplay: true,
      carousel_speed: 4500,
      pause_on_hover: true,
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  about: {
    type: 'about',
    title: 'About Me',
    description: 'Personal portrait, story, development philosophy, specialized tech stack, and booking availability.',
    category: 'core',
    iconName: 'User',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Meet the Shopify Expert',
      heading: 'I Build Shopify Stores That Sell',
      description:
        "I'm Ansarul Anis — a Shopify expert who helps ambitious brands build Shopify websites that convert. From Shopify store design to dropshipping store builds and full ecommerce website development, I engineer every pixel for revenue.",
      image_url: '/images/shopify-dashboard.png',
      image_position: 'left',
      availability_line: 'Currently booking for this month',
      tools: [
        'Shopify 2.0',
        'Liquid',
        'React / Next.js',
        'Tailwind CSS',
        'Storefront API',
        'Figma',
        'Klaviyo',
        'Recharge',
      ],
      badge_top_title: 'Top Rated',
      badge_top_subtitle: 'Shopify Developer',
      badge_bottom_title: '270+ Stores',
      badge_bottom_subtitle: 'Developed Successfully',
      layout: 'two-column',
      background: 'muted',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  faq: {
    type: 'faq',
    title: 'FAQ Section',
    description: 'Pre-answer client objections on pricing, timelines, warranty, and development process.',
    category: 'core',
    iconName: 'HelpCircle',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Common Questions',
      heading: 'Shopify Website Design & Development FAQ',
      subheading: 'Everything you need to know about working with a Shopify expert — timelines, pricing, process, and support.',
      accordion_allow_multiple: false,
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  contact: {
    type: 'contact',
    title: 'Contact / Inquiry Form',
    description: 'Lead capture form with project type, budget estimation, and direct WhatsApp chat card.',
    category: 'core',
    iconName: 'Mail',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Start Your Shopify Project',
      heading: 'Ready to Build Your Shopify Store?',
      subheading:
        'Tell me about your brand and goals. Whether you need Shopify store setup, a store redesign, or a dropshipping store, I reply within 24 hours with a detailed scope.',
      whatsapp_number: '+8801709260934',
      whatsapp_prefill: 'Hi Anis! I visited your portfolio and I would like to discuss a Shopify project.',
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  footer: {
    type: 'footer',
    title: 'Footer',
    description: 'Bottom brand identity, navigation anchor links, social links, and copyright statement.',
    category: 'core',
    iconName: 'Layers',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: false,
      supportsSpacing: false,
      supportsAnimation: false,
      supportsVisibility: true,
    },
    defaultSettings: {
      heading: 'AnisShopify',
      description:
        'Ansarul Anis — Shopify expert specializing in Shopify store design, Shopify website development, ecommerce website builds, and dropshipping store setups.',
      show_social_icons: true,
      copyright_text: '',
      background: 'default',
    },
  },
  exit_popup: {
    type: 'exit_popup',
    title: 'Exit Intent Visitor Popup',
    description: 'Visitor retention exit-intent modal with custom hook, heading, WhatsApp chat, and lead capture form.',
    category: 'core',
    iconName: 'Sparkles',
    capabilities: {
      supportsContent: true,
      supportsLayout: false,
      supportsStyle: false,
      supportsTypography: false,
      supportsSpacing: false,
      supportsAnimation: false,
      supportsVisibility: true,
    },
    defaultSettings: {
      exit_popup_enabled: true,
      exit_popup_eyebrow: 'WAIT! BEFORE YOU GO',
      exit_popup_title: "Let's Build Your Dream Shopify Store",
      exit_popup_subheading: 'Get a Free 15-Minute Shopify Audit & Fixed Quote for your project. Reach out on WhatsApp or drop a quick line below!',
      exit_popup_whatsapp_label: 'Chat on WhatsApp',
      exit_popup_whatsapp_tag: '',
      exit_popup_submit_label: 'Get Free Audit & Quote',
    },
  },
  cta: {
    type: 'cta',
    title: 'Call to Action Banner',
    description: 'High-contrast conversion strip encouraging visitors to initiate a project.',
    category: 'content',
    iconName: 'Zap',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Let\'s Get Started',
      heading: 'Need a Shopify Expert for Your Ecommerce Website?',
      subheading: 'Book a free 20-minute store audit or discuss your Shopify website development project directly with me.',
      primary_cta_label: 'Get a Free Scope Estimate',
      primary_cta_url: '#contact',
      secondary_cta_label: 'WhatsApp Quick Chat',
      secondary_cta_url: '#contact',
      background: 'accent',
      spacing_top: 'normal',
      spacing_bottom: 'normal',
      animation: 'scale',
    },
  },
  text_image: {
    type: 'text_image',
    title: 'Text + Image Split',
    description: 'Two-column presentation featuring explanatory copy alongside a store mockup or diagram.',
    category: 'content',
    iconName: 'Columns',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Speed & Architecture',
      heading: 'Engineered for Sub-Second Mobile PageSpeed',
      description:
        'Every millisecond of latency costs conversions. I audit Liquid rendering trees, eliminate third-party render-blocking scripts, and compress responsive assets so your store loads instantly.',
      image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
      image_position: 'right',
      primary_cta_label: 'Learn More',
      primary_cta_url: '#contact',
      layout: 'two-column',
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
    },
  },
  stats: {
    type: 'stats',
    title: 'Statistics Grid',
    description: 'Grid of prominent numbers and achievements with labels.',
    category: 'content',
    iconName: 'BarChart3',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
      supportsBlocks: true,
    },
    defaultSettings: {
      heading: 'Proven Metrics Across DTC Brands',
      subheading: 'Measured improvements delivered across client storefronts in the last 12 months.',
      layout: 'four-column',
      background: 'default',
      spacing_top: 'normal',
      spacing_bottom: 'normal',
      blocks: [
        { id: 'b-1', type: 'stat', stat_value: '+171%', stat_label: 'Mobile Conversion Rate' },
        { id: 'b-2', type: 'stat', stat_value: '0.8s', stat_label: 'Avg. First Contentful Paint' },
        { id: 'b-3', type: 'stat', stat_value: '$4.2M+', stat_label: 'Client GMV Processed' },
        { id: 'b-4', type: 'stat', stat_value: '100%', stat_label: 'Native Liquid Compliance' },
      ],
      animation: 'fade-up',
    },
  },
  logo_strip: {
    type: 'logo_strip',
    title: 'Brand / Logo Strip',
    description: 'Row or marquee of client brands, technology logos, or certifications.',
    category: 'content',
    iconName: 'ShieldCheck',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: false,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      eyebrow: 'Trusted By DTC Founders',
      heading: 'Stores Built & Optimized Across Industries',
      background: 'muted',
      spacing_top: 'compact',
      spacing_bottom: 'compact',
      animation: 'fade',
    },
  },
  gallery: {
    type: 'gallery',
    title: 'Image Gallery',
    description: 'Visual showcase grid of desktop and mobile storefront screen designs.',
    category: 'media',
    iconName: 'Image',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
      supportsBlocks: true,
    },
    defaultSettings: {
      eyebrow: 'Visual Portfolio',
      heading: 'Crafted Storefront Interfaces',
      layout: 'grid',
      columns: 3,
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      blocks: [
        {
          id: 'g-1',
          type: 'image',
          image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
          title: 'Skincare E-Commerce UI',
        },
        {
          id: 'g-2',
          type: 'image',
          image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
          title: 'Performance Cycling Landing Page',
        },
        {
          id: 'g-3',
          type: 'image',
          image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
          title: 'Nordic Furniture Headless Store',
        },
      ],
      animation: 'fade-up',
    },
  },
  video: {
    type: 'video',
    title: 'Video Showcase',
    description: 'Embedded video player showcasing store interactions or a founder intro.',
    category: 'media',
    iconName: 'Video',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
    },
    defaultSettings: {
      heading: 'See It in Action: Conversion Flow Walkthrough',
      subheading: 'Watch how sub-second page loads and direct-response carts double checkout completion.',
      video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      background: 'default',
      spacing_top: 'normal',
      spacing_bottom: 'normal',
      animation: 'fade-up',
    },
  },
  spacer: {
    type: 'spacer',
    title: 'Spacer / Divider',
    description: 'Clean visual whitespace divider with optional subtle hairline border.',
    category: 'layout',
    iconName: 'SeparatorHorizontal',
    capabilities: {
      supportsContent: false,
      supportsLayout: false,
      supportsStyle: true,
      supportsTypography: false,
      supportsSpacing: true,
      supportsAnimation: false,
      supportsVisibility: true,
    },
    defaultSettings: {
      spacing_top: 'normal',
      spacing_bottom: 'normal',
      background: 'default',
    },
  },
  custom: {
    type: 'custom',
    title: 'Custom Section',
    description: 'Dynamic section builder combining text blocks, images, buttons, stats, and cards.',
    category: 'content',
    iconName: 'LayoutGrid',
    capabilities: {
      supportsContent: true,
      supportsLayout: true,
      supportsStyle: true,
      supportsTypography: true,
      supportsSpacing: true,
      supportsAnimation: true,
      supportsVisibility: true,
      supportsBlocks: true,
    },
    defaultSettings: {
      eyebrow: 'Why Work With Me?',
      heading: 'Direct Developer Partnership Without the Agency Overhead',
      subheading: 'Work directly with the person who codes your theme, designs your flows, and guarantees your Core Web Vitals.',
      layout: 'three-column',
      columns: 3,
      background: 'default',
      spacing_top: 'spacious',
      spacing_bottom: 'spacious',
      animation: 'fade-up',
      blocks: [
        {
          id: 'cb-1',
          type: 'card',
          title: 'Zero Bloat Liquid',
          text: 'Clean native Shopify 2.0 architecture with no unnecessary third-party apps slowing down your checkout.',
          icon: 'Code2',
        },
        {
          id: 'cb-2',
          type: 'card',
          title: 'Direct-Response CRO',
          text: 'Every section is designed according to proven conversion psychology to drive maximum average order value.',
          icon: 'Target',
        },
        {
          id: 'cb-3',
          type: 'card',
          title: '30-Day Post-Launch Warranty',
          text: 'Complete peace of mind with 30 days of complimentary code fixes and conversion tracking verification.',
          icon: 'ShieldCheck',
        },
      ],
    },
  },
};

export const initialDefaultSections: PageSection[] = [
  {
    id: 'sec-nav',
    page_key: 'home',
    section_key: 'home_navigation',
    section_type: 'navigation',
    title: 'Global Navigation',
    order_index: 0,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.navigation.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-hero',
    page_key: 'home',
    section_key: 'home_hero',
    section_type: 'hero',
    title: 'Hero Banner',
    order_index: 1,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.hero.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-trust',
    page_key: 'home',
    section_key: 'home_trust_bar',
    section_type: 'trust_bar',
    title: 'Trust Bar',
    order_index: 2,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.trust_bar.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-work',
    page_key: 'home',
    section_key: 'home_work',
    section_type: 'work',
    title: 'Case Studies / Work',
    order_index: 3,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.work.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-services',
    page_key: 'home',
    section_key: 'home_services',
    section_type: 'services',
    title: 'Services',
    order_index: 4,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.services.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-testimonials',
    page_key: 'home',
    section_key: 'home_testimonials',
    section_type: 'testimonials',
    title: 'Client Testimonials',
    order_index: 5,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.testimonials.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-about',
    page_key: 'home',
    section_key: 'home_about',
    section_type: 'about',
    title: 'About Developer',
    order_index: 6,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.about.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-faq',
    page_key: 'home',
    section_key: 'home_faq',
    section_type: 'faq',
    title: 'FAQ',
    order_index: 7,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.faq.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-contact',
    page_key: 'home',
    section_key: 'home_contact',
    section_type: 'contact',
    title: 'Contact / Project Scope',
    order_index: 8,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.contact.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-footer',
    page_key: 'home',
    section_key: 'home_footer',
    section_type: 'footer',
    title: 'Footer',
    order_index: 9,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.footer.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-exit-popup',
    page_key: 'home',
    section_key: 'home_exit_popup',
    section_type: 'exit_popup',
    title: 'Exit Intent Visitor Popup',
    order_index: 10,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: SECTION_DEFINITIONS.exit_popup.defaultSettings,
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function createNewSection(type: SectionType, existingCount: number): PageSection {
  const def = SECTION_DEFINITIONS[type] || SECTION_DEFINITIONS.custom;
  const timestamp = Date.now();
  return {
    id: `sec-${type}-${timestamp}`,
    page_key: 'home',
    section_key: `home_${type}_${timestamp.toString(36)}`,
    section_type: type,
    title: def.title,
    order_index: existingCount,
    is_enabled: true,
    is_visible: true,
    desktop_visible: true,
    tablet_visible: true,
    mobile_visible: true,
    status: 'published',
    settings: JSON.parse(JSON.stringify(def.defaultSettings)),
    draft_settings: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
}
